### PR TITLE
Update 0_setup.sh

### PR DESCRIPTION
**Pull request by Smiril**

### CODE REVIEW

**Comment by kingkelo** [comment]
Hello, I used your branch, but I had problems installing and running it.

kl@KL-Macbook-Pro scripts % /Users/kl/DeepFaceLab_MacOS/scripts/2_extract_images_from_video_data_src.sh
Would you like to run script in python3.11 mode? (yes or no)

Not a valid answer.
kl@KL-Macbook-Pro scripts % /Users/kl/Sites/deepfacelab/DeepFaceLab_MacOS/workspace/data_src.mp4 /Users/kl/Sites/deepfacelab/DeepFaceLab_MacOS/workspace/data_dst.mp4
zsh: permission denied: /Users/kl/Sites/deepfacelab/DeepFaceLab_MacOS/workspace/data_src.mp4
kl@KL-Macbook-Pro scripts % /Users/kl/DeepFaceLab_MacOS/scripts/2_extract_images_from_video_data_src.sh
Would you like to run script in python3.11 mode? (yes or no)
no
Will run in python3.10 mode
/Users/kl/DeepFaceLab_MacOS/scripts/2_extract_images_from_video_data_src.sh: line 5: python: command not found
kl@KL-Macbook-Pro scripts % 

can you help me？ thank 

> `you```

**Comment by Smiril** [comment]
brew install python3.10
brew install python3.11

did you have python installed?

**Comment by kingkelo** [comment]
Yes, I use 0_setup. This script installed python3.10, the installation directory is .dfl/env/lib/python3.10, and my homebrew directory also has python3.10 installed

**Comment by Smiril** [comment]
#!/usr/bin/env bash
cd "$(dirname $0)/.."
source scripts/env.sh

python "$DFL_MAIN" videoed extract-video \
  --input-file "$WORKSPACE/data_src.*" \
  --output-dir "$WORKSPACE/data_src"

thats line 5 so python or $DFL_MAIN not found

**Comment by Smiril** [comment]
did you ....

source .dfl/env/bin/activate

????

**Comment by Smiril** [comment]
additional you can run 0_patch.sh

**Pull request closed without merging**
